### ISSUE TITLE
Setup Frontend Dev Workflow

### ISSUE THREAD

**Issue by matsilva** [coderie/coderie-site#6]
Should have: 
- Guide to setup webpack and other frontend dependencies
- Guide on adding new js entry points, covering naming conventions.
- Guide on working with new modules and cover code splitting & chunking dependencies
- Guide on working with .scss and compiling to css

**Comment by matsilva** [comment]
Resolved in: https://github.com/coderie/coderie-site/pull/8

**Comment by matsilva** [comment]
Sort of resolved.. .scss workflow needs to be covered... any takers?

**Comment by htmelvis** [comment]
I will setup the sass loader and .scss workflow

**Comment by matsilva** [comment]
Awesome man thanks
